#!/usr/bin/env python

##################################################################
# OpenKeyval command line interface!
# Here are some example calls:
# okv set -k someKey -v someVal
# okv del -k someKey 
# okv get -k someKey 
##################################################################

import sys, os
from optparse import OptionParser
from pyopenkeyval.pyopenkeyval import pyopenkeyval

def run():
  # Usage message for --help or errors
  usage = "Usage: %prog [set|get|del] [args]"

  # Get the values from the command line.
  parser = OptionParser(usage=usage)
  options = parse_arguments(parser)

  # Get the key prefix 
  prefix = get_key_prefix(options, parser)

  # Exit out if operation not provided
  if len(sys.argv) < 2:
    parser.error("No operation was provided. Run `okv --help` for more info.")
    exit(1)

  operation = sys.argv[1]

  if operation == 'set': 
    execute_set(prefix, options, parser)
  elif operation == 'get':
    execute_get(prefix, options, parser)
  elif operation == 'del':
    execute_del(prefix, options, parser)
  else:
    parser.error("Incorrect operation provided.")

# Set command line parser options
def parse_arguments(parser):
  parser.add_option("-k", "--key", dest="key", help="Key")
  parser.add_option("-v", "--value", dest="value", help="Value")
  parser.add_option("-n", "--no-prefix", action="store_true", dest="noPrefix", 
      help="Do not use the prefix from the OKV_PREFIX environment variable")

  (options, args) = parser.parse_args(sys.argv)
  return options

# Validate and execute the get operation
def execute_get(prefix, options, parser):
  if options.key == None:
  	parser.error("Key required")
  	exit(1)
  okv = pyopenkeyval()
  key = "%s%s" %(prefix, options.key)
  print(okv[key])

# Validate and execute the set operation
def execute_set(prefix, options, parser):
  if options.key == None:
    parser.error("Key requried")
    exit(1)
  if options.value == None:
    parser.error("Value requried")
    exit(1)
  okv = pyopenkeyval()
  key = "%s%s" %(prefix, options.key)
  okv[key] = options.value

# Validate and execute the del operation
def execute_del(prefix, options, parser):
  if options.key == None:
    parser.error("Key required")
    exit(1)
  okv = pyopenkeyval()
  key = "%s%s" %(prefix, options.key)
  del okv[key]


# Get the key prefix
def get_key_prefix(options, parser):
   # If the user specified to not use a prefix, return an empty string
   # as the prefix. Otherwise, attempt to return the OKV_PREFIX environment
   # variable as the prefix
   if options.noPrefix:
     return ''
   else:
     if "OKV_PREFIX" in os.environ.keys():
       return os.environ["OKV_PREFIX"]
     else:
     	 print("OKV_PREFIX environment variable not found but -n not passed")
     	 exit(1)

# Specifal function to covert items to strings, with a special consideration
# of None
def xstr(s):
  return '' if s is None else str(s)
if __name__ == "__main__":
	run()

