#!/usr/bin/env python

##################################################################
# OpenKeyval command line interface!
# Here are some example calls:
# okv set -k someKey -v someVal
# okv del -k someKey 
# okv get -k someKey 
##################################################################

import sys
from optparse import OptionParser
from pyopenkeyval.pyopenkeyval import pyopenkeyval

def run():
  okv = pyopenkeyval()

  # Usage message for --help or errors
  usage = "Usage: %prog [set|get|del] [args]"

  # Get the values from the command line.
  parser = OptionParser(usage=usage)
  options = parse_arguments(parser)

  # Get the key prefix 
  prefix = get_key_prefix(options, parser)

  # Exit out if operation not provided
  if len(sys.argv) < 2:
    parser.error("No operation was provided. Run `okv --help` for more info.")
    exit(1)

  operation = sys.argv[1]

  if operation == 'set': 
    execute_set(options, parser)
  elif operation == 'get':
    execute_get(options, parser)
  elif operation == 'del':
    execute_del(options, parser)
  else:
    parser.error("Incorrect operation provided.")

# Set command line parser options
def parse_arguments(parser):
  parser.add_option("-k", "--key", dest="key", help="Key")
  parser.add_option("-v", "--value", dest="value", help="Value")
  parser.add_option("-n", "--no-prefix", action="store_true", dest="noPrefix", 
      help="Do not use the prefix from the OKV_PREFIX environment variable")

  (options, args) = parser.parse_args(sys.argv)
  return options

# Validate and execute the get operation
def execute_get(options, parser):
  print("Getting %s!" % options.key)

# Validate and execute the set operation
def execute_set(options, parser):
  print("Setting %s!" % options.key)

# Validate and execute the del operation
def execute_del(options, parser):
  print("Deleting %s!" % options.key)


# Get the key prefix
def get_key_prefix(options, parser):
   # If the user specified to not use a prefix, return an empty string
   if options.noPrefix:
   	 return ""


if __name__ == "__main__":
	run()

